### ISSUE TITLE
$ionicAuth.login promise missing finally feature to be angular consistent

### ISSUE THREAD

**Issue by astik** [driftyco/ionic-platform-web-client#110]
I can see by logging to the console (remote debug) that the promise returned by $ionicAuth.login is a lib$es6$promise$promise$$Promise.
This object has 2 methods : then and catch.
It is missing the finally promise in order to be consistent with the Angular way of handling promise. Maybe $ionicAuth should take care of this in order to wrap the ES6 promise.
Though, I may be missing something ...

**Comment by morellan** [comment]
I think this is related with my PR #116 , I had the same problem and found a quick and easy fix

**Comment by dwieeb** [comment]
We use a number of vanilla A+ promises in our client. For the Angular 1 integration, we _should_ be wrapping them in angular's promises, not only for the finally feature, but more importantly so that angular change detection would work. This may be a bit of an undertaking, so I've made an issue in the new Ionic Cloud client repo: https://github.com/driftyco/ionic-cloud/issues/4
