### ISSUE TITLE
ipad2 ios9 push notification app:{asleep, closed} not functioning as advertised

### ISSUE THREAD

**Issue by gravity-addiction** [driftyco/ionic-platform-web-client#13]
within the push onNotification: function(notification)
"app":{"closed":false} never gets changed to "closed": true .. case scenarios from opening or returning to app when clicking on the incoming notification. first case being in the app, ipad2 awake, this case had no user interaction needed to open or return to app. the first, second and fourth cases seem to be the only correct cases.

1. app open, app in foreground - "app":{"asleep":false,"closed":false}
2. app open, app in foreground, sleep mode - "app":{"asleep":true,"closed":false}
3. app open, app in background, awake - "app":{"asleep":true,"closed":false}
4. app open, app in background, sleep mode - "app":{"asleep":true,"closed":false}
5. app closed, awake - "app":{"asleep":true,"closed":false}
6. app closed, sleep mode - "app":{"asleep":true,"closed":false}

Separate Note;
There is a foreground identifier in _raw.additionalData that would be useful within the "app" object.

**Comment by Ionitron** [comment]
Greetings @gravity-addiction!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
