### ISSUE TITLE
Push notification not registering

### ISSUE THREAD

**Issue by ljayz** [driftyco/ionic-platform-web-client#130]
I'm following push notification setup tutorial from [ionics documentaton](http://docs.ionic.io/docs/push-full-setup) but after running the app on android device, the app unable to register. 

Here is the logcat error:
>Uncaught TypeError: Cannot call method 'on' of undefined", 
>source: file:///android_asset/www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js (3)

I changed the src to not minified version to see where the error comes
>self._emitter.on('ionic_push:ready', function () {   //line 6147
>    callback(self);
>});

The code does not seem to register the 'on' function

Any help? Thank you

**Comment by alex-mazzariol** [comment]
I've seen this happening because the Push() constructor did not set the devPush and/or gcmKey properties on the IonicApp object. The problem is that the coreLogger does not log anything to the console beyond the prefix, so my console was full of "Ionic Push:" rows without any content.

The message "GCM project number not found (http://docs.ionic.io/docs/push-android-setup)" would have appeared, and I would have known what was wrong.

I had to configure my copy of ionic.io.bundle.js by hand, because of a chain of problems with the automagic `ionic add ionic-platform-web-client` and `ionic plugin add phonegap-plugin-push` commands, which both fail as of now in ionic CLI 2.0.0-beta.32.

It'd be extremely useful if the documentation (both for limited and full push config) mentioned that one can configure everything by hand, by doing some simple steps:
* you need the ionic.io.bundle.js or ionic.io.bundle.min.js files imported in your html after ionic bundle.
* you don't need to explicitly include cordova.js, because it will be imported from ionic.io.bundle.
* you should search for the strings "IONIC_SETTINGS_STRING_START" and "IONIC_SETTINGS_STRING_END" and put an object like the following between those strings:
```
var settings = {
    app_id:"YOUR_APP_ID",
    api_key:"YOUR_API_KEY",
    dev_push: false,
    gcm_key:"YOUR_GOOGLE_CLOUD_KEY"
};
return { get: function(setting) { if(settings[setting]) { return settings[setting]; } return null; } };

```

If you are in dev_push mode, set the boolean accordingly. If you set it to false, remember to set gcm_key to some meaningful value.

If you are trying to have it configure on its own (i.e. `ionic io init`) but it fails to find/update the files, you can find a `.io-config.json` file in your project root, which contains the app_id and api_key constants.

**Comment by dwieeb** [comment]
@ljayz @alex-mazzariol `ionic-platform-web-client` is deprecated. We are asking that people migrate to [the Cloud Client](https://github.com/driftyco/ionic-cloud). Hopefully with the new config system it is much easier. Take note of the migration guide.
