### ISSUE TITLE
Custom directories installation problem 

### ISSUE THREAD

**Issue by przemkow** [driftyco/ionic-platform-web-client#132]
Hi, 
I'm trying to integrate your plugin with my app but unfortunately i bump into a problem because of my directory structure.  At first after running `ionic add ionic-platform-web-client` i have got:
```
Bower component installed - ionic-platform-web-client
ERROR:  Error: ENOENT: no such file or directory, open './www/js/app.js'
    at Error (native)
Is your app declaration contained in 'app.js'?
```

and it's obvious there is no `./www/js/app.js`  because all of my app files are in `./app/src/`, beside that all bower plugins are stored in `./bower_components` directory. for building a project i use two tasks in gulp `build` which takes all bower dependencies and `dist` to create one minified .js file with everything.

I would be very grateful if you could help me how can i configure ionic-platform-web-client plugin to use path which i have in my project? I was trying to find workaround but i can not find any good solution for my problem. 

I use:
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v4.4.4
```

**Comment by ericb** [comment]
You'll need to setup the `www` structure temporarily, so that the configuration can be written correctly. You can then copy the generated files over to your custom directory. We talk about this a bit in our  [docs](http://docs.ionic.io/v2.0.0-beta/docs/io-service-modules#automatic-code-modification).

This is all going away with our new [cloud client](https://github.com/driftyco/ionic-cloud). It's available for you to use today, but we have not published full documentation for it yet as we have yet to release a stable version. Having said that, it is the future of the client library for Ionic Cloud, and you may find it better to start using it now rather than later.

**Comment by przemkow** [comment]
ohh great, it's pretty cool that this problem is solved in cloud client :) luckily i've managed to setup your plugin with my project but changing manually files from bower_components is definitely not a good practice. it would be much more better to just have simple config file somewhere instead of doing workaround like this :)
