### ISSUE TITLE
Pass a User to push.unregister()

### ISSUE THREAD

**Issue by santimacia** [driftyco/ionic-platform-web-client#20]
The register accepts a user with a id field, but is that possible with unregister?

**Comment by ericb** [comment]
Register does *not* in fact take a user id. (Our older ionic-service-push did), but rather, `register` just registers the *device* with GCM/APNS. This for all intents and purposes, just gives you a device token which can be used to send push notifications to that device. `unregister` will *invalidate* a token in our system. This means that if we get a request to send to that token, we will block the attempt. This also sends an unregister request to GCM/APNS, but tokens will still be valid for some unknown amount of time. This is why `unregister` takes a device token, because it's just as agnostic to a user as register() is.

However, the user class does have a `removePushToken` method which can be used to remove a token reference from a user. This is not the same as `unregister`, where the token is invalidated.
