### ISSUE TITLE
[Push] Development Mode breaks with Chrome Dev Tools and "Device mode"

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-platform-web-client#22]
If you use [Chrome Dev Tools' "Device Mode"](https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode/) to simulate an Android or iOS device Development Mode of Ionic Push breaks (ionic-platform-web-client 0.2.0).

When you follow the [Push from Scratch guide](http://docs.ionic.io/docs/push-from-scratch) and then enable Device Mode for e.g. iPhone 6 you only get the following in the console:

> Ionic Core: init
> Ionic Core: searching for cordova.js
> Ionic Core: attempting to mock plugins
> Ionic Push: register

Then nothing happens. As soon as you disbale Device Mode, everything works as expected and you get the expected output:

> Ionic Push (dev): registered with development push service
> Ionic Push: (debug) device token registered: <PushToken ['DEV-61970...a1']>
> Device token: DEV-61970e78-d437-4c09-af1c-288a3c4a3fa1
> Ionic Push (dev): watching for new notifications

I assume the Ionic Push code somehow goes a different code path when device is iOS or Android, then something fails as we are not on a real device but there is no error message logged for whatever reason.

As I assume using Device Mode in Chrome Dev Tools is one of the default ways to develop Ionic apps this could confuse many developers. Would be great if this could be fixed. Until the easy workaround is to disable Device Mode.

**Comment by ericb** [comment]
You are correct, when you set a specific type of mobile device in chrome dev tools, it makes the code behave as though we are on a specific device. This doesn't actually break anything per se, but the service is now waiting for cordova plugins to ready themselves (something that will never happen since we are not on a physical device).

Until we can reliably detect that the chrome mobile emulation is being used, and not an actual physical device there isn't much we can do about this. Having said that, you can manually trigger the plugins_ready event (though there is no guarantee that there won't be other quirks):

`Ionic.Core.getEmitter().emit('ionic_core:plugins_ready');`

**Comment by piotrowski** [comment]
Yeah, doesn't help much as the Ionic Push code then is still looking for stuff that isn't there:

> $ Ionic.Core.getEmitter().emit('ionic_core:plugins_ready');
> (x) Ionic Push: PushNotification plugin is required. Have you run `ionic plugin add phonegap-plugin-push` ?
> (x) Uncaught ReferenceError: PushNotification is not defined

As I am running this through `ionic serve`, wouldn't this be a way to tell the code that we are not actually on a real device?

**Comment by barocsi** [comment]
+1 from https://github.com/driftyco/ionic-platform-web-client/issues/47

**Comment by mlynch** [comment]
@ericb wanted to chime in here as we handle this in Ionic proper with `Platform.isWebView` to detect when we're running on the device. This will not fail in chrome emulation and would probably resolve this.

**Comment by ashishtilara** [comment]
+1
