### ISSUE TITLE
Issues when trying to import with Webpack

### ISSUE THREAD

**Issue by dmackerman** [driftyco/ionic-platform-web-client#37]
When using a loader such as Webpack, this library doesn't seem to play nice.

```js
import 'ionic-platform-web-client/dist/ionic.io.bundle';
```

Few things:

- missing a `main` entry in `package.json`
- Webpack throws a nice error to warn that this is a pre-built file, but the source files aren't setup to be module loaded in this way.
- this should be a fix for other module loaders out there, like SystemJS and Browserify

```bash
WARNING in ./~/ionic-platform-web-client/dist/ionic.io.bundle.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/ionic-platform-web-client/dist/ionic.io.bundle.js 1:113-120
```

**Comment by tannerlinsley** [comment]
Were you able to successfully import the pre-built file anyway and use it?

**Comment by dmackerman** [comment]
We ended up importing `angular` and `ionic` separately. 

```
import 'angular/angular';
import 'angular-animate/angular-animate';
import 'angular-sanitize/angular-sanitize';
import 'ionic-sdk/release/js/angular-ui/angular-ui-router';
import 'ionic-sdk/release/js/ionic';
import 'ionic-sdk/release/js/ionic-angular';
```

**Comment by izeau** [comment]
Hi guys, I’m encountering a similar issue with browserify. I see you imported the ionic & ionic-angular files but not the ionic.io.bundle, how did you handle that? `import 'ionic-platform-web-client/dist/ionic.io.bundle` still doesn’t seem to work. Thanks!

**Comment by dmackerman** [comment]
@izeau we wanted to use Angular 1.5, so we imported all the dependencies seperately, and then just `ionic` and not the `ionic.bundle`. We haven't run into any issues.

**Comment by izeau** [comment]
Alright, that’s the bit I was concerned about. May I ask you how you did achieve Ionic User / Push integration?

**Comment by dmackerman** [comment]
We haven't gotten there yet, but I don't think we'll be using the ionic.io services. :cry:

**Comment by ericb** [comment]
Hey guys, i'm not super familiar with Webpack, but I believe you should be able to import the exported classes directly from the src files:

For example, if you wanted to get the Ionic.User and Ionic.Push you would import the classes from the user and push src files:

```javascript
import {User} from 'ionic-platform-web-client/src/core/user';
import {Push} from 'ionic-platform-web-client/src/push/push';
```

But perhaps I'm missing some necessary information from Webpack configuration. 

Either way I'm happy to work on updates as necessary so that we can integrate nicely with Webpack.

**Comment by izeau** [comment]
We can’t import directly from `ionic-platform-web-client/<anything>` because babel needs to be configured correctly in `ionic-platform-web-client`’s `package.json`. Anyway, even if we could we wouldn’t be able to use it because of the way the settings are injected.

What I did end up with was this hack:

```
gulp.task('vendor:io', function () {
  var io = env === 'production'
    ? './node_modules/ionic-platform-web-client/dist/ionic.io.bundle.min.js'
    : './node_modules/ionic-platform-web-client/dist/ionic.io.bundle.js';

  var before = /"IONIC_SETTINGS_STRING_START.*IONIC_SETTINGS_STRING_END"/;
  var after  = [
    '"IONIC_SETTINGS_STRING_START";',
    'var settings = ' + JSON.stringify({
      app_id: config.ionicAppId,
      api_key: config.ionicApiKey
    }) + ';',
    'return { get: function (key) { return settings[key] || null; } };',
    '"IONIC_SETTINGS_STRING_END";'
  ].join('');

  return gulp
    .src(io)
    .pipe(replace(before, after))
    .pipe(gulp.dest('./www'));
});
```

And then reference directly the script in the HTML. Not really satisfying but hey, it works…

**Comment by dwieeb** [comment]
Guys, please try importing via webpack with the cloud client (the future of the `ionic-platform-web-client`): https://github.com/driftyco/ionic-cloud

It exports es5 commonjs and has `main` entry in `package.json`. Should play very nicely. 

Closing this as I believe it is addressed. Let me know otherwise.
