### ISSUE TITLE
Platform Configuration Discussion

### ISSUE THREAD

**Issue by ericb** [driftyco/ionic-platform-web-client#41]
@kylefox @AgDude @glasset @Jerome2606 @tlancina @dwieeb @Fuiste 

Hey everyone,

I'm opening this up to discuss what we can do to make the Ionic Platform configuration make sense for a wider audience. I'd like to hear different use-cases and how the config currently helps or hinders those of you who don't quite fit in the "just use the default Cordova structure" crowd. 

So with that in mind, my goal here is to develop a plan to migrate the Platform configuration to a new solution that will suit as many use-cases as possible while still remaining something that is:

    a. easy to grok
    b. easy to use
    c. easy to extend

Okay, so let's talk about some restrictions:

* The config should still maintain a JSON structure
* The config should not be reliant on any frameworks (including Ionic)
* The config should values should be treated as constants as much as possible.
* The config location should be a standalone file (it is not currently)

Here are some things we should consider:

* Will the config fit in a developers custom workflow
* Can the configuration be giving by a 3rd party
* How should the Platform discover the config.
* Does the config need to be defined pre-instantiation of the platform code? (likely yes)

And here are some info on the current config (both good and bad):

* The config is built into a platform dependency file (this means the lib file included for one project is not the same as another)
* We have a hidden standalone JSON file which contains the config (but it is not used in the application)
* The config only allows custom values via the CLI, but the actual configuration can include anything. 

I just threw this together so there may be things I'm not thinking about and the restrictions are only restrictions as much as I consider them to be at the moment -- if anyone can provide a compelling argument for _anything_, so be it.

Please, _please_ ask questions, ask for clarifications on things you don't quite understand, and offer up your personal suggestions. This is an open discussion, feel free to chime in with your thoughts (I'm talking to you, random developer reading this)

Cheers :beers:

**Comment by AgDude** [comment]
Eric, thanks for starting the discussion.

Before  I go into details about some suggestions, I want to comment on the "cordova default crowd." Cordova has become popular become the barrier to entry is extremely low. This means someone who doesn't know what a "build process" is can write an app. That is a good thing. As an experienced software developer I have some expectations about how a project structure and build process should work. One of those expectations is that I can delete everything in a "dist" folder and regenerate those file ("dist" happens to be called "www" in cordova). Another expectation is that something installed as a dependency is simply a library. Libraries should not include my (potentially confidential) configuration. Not that I would suggest doing this, but one should be able to simply copy a node module from one project to another.

Currently I am working on an Ionic based app. At the top level of my project I have a "www" folder, "src" folder and a "lib" folder (which others might call "bower_components").  "www" is excluded from git.  I use gulp to completely clean the "www" folder before every build, bundle the app and the dependencies together into a single js file called "app.bundle.js" which is placed into "www". When I am developing/testing I have gulp tasks to put other files into www which are easier to debug and might include mocks/shims for cordova. This setup is not too different from what one might use for developing a web application.

My requirements are that I can build the app on any machine simply by calling `npm install; bower_install; gulp build` Whether that be another developers computer, a new vagrant instance, or a CI platform.

So for my suggestions.
**use angular constants**
You can use a gulp task to build the constants from a json file (I currently do this for our API keys for various platforms, with different configs for testing/dev/staging...). You could provide a CLI command to generate the `json` file and a `.js` file with the constant already defined (so a user who doesn't know what gulp is wouldn't have to copy/paste). 

You could also accept the config object as an argument to `Ionic.io()`, which would allow uses not using angular to configure it however they want (this would have to added benefit of allowing the config to be fetched remotely at runtime).

If you want to keep your current opaque system. Do all three, setting a clearly documented order of priority of where the config comes from.

1. get the config from the arguments
2. Look for the angular constant called "IONIC_IO_CONFIG"
3. See if it was put into the js file at install time.

**Comment by ericb** [comment]
@AgDude This is exactly the kind of feedback I'm looking for, thank you for taking the time to write up your thoughts and suggestions. 

At a preliminary glance, I really like some of the suggestions you've made (specifically setting a precedence order for configuration loading + injection of the configuration).

**Comment by kylefox** [comment]
First off, I totally agree with @AgDude — I want to treat `www` as a transient, volatile directory. No code should be written there. It should only consist of the files/code required to run the app, and all of those files should be _generated_ and as minimal as possible (especially in production builds). As I mentioned in another issue, my `www` was ~14MB due to the bower component tree. My way around this was to move bower components to `./bower_modules` and then manually specify the exact files to bundle into `www` using gulp.

My configuration setup was inspired by Rail's use of YAML files grouped by _environment_, as well as some blog posts I read about Ionic specifically.

First, I have `./environments.json` sitting in my project root. It is intended to be _totally agnostic_ around tooling & frameworks. It's just a JSON file. It looks something like this (slimmed down):

```json
{
  "development": {
    "LOG_LEVEL": "debug",
    "API_BASE_URL": "http://localhost:8000/api",
  },
  "staging": {
    "LOG_LEVEL": "info",
    "API_BASE_URL": "https://api-dev.example.com/api",
  },
  "production": {
    "LOG_LEVEL": "error",
    "API_BASE_URL": "https://api.example.com/api",
  }
}
```

I define an Angular constant with placeholder strings in `./app/config.js`

```javascript
angular.module('app.config', [])

.constant('Config', {
  LOG_LEVEL: '@@LOG_LEVEL',
  API_BASE_URL: '@@API_BASE_URL',
  VERSION: '@@VERSION',
  BUILD_DATE: '@@BUILD_DATE',
})
```

which is compiled by a gulp task (shown further down) into `./www/js/config.js`

```javascript
angular.module('cn.config', [])

.constant('Config', {
  LOG_LEVEL: 'debug',
  API_BASE_URL: 'http://localhost:8000/api',
  VERSION: '0.0.4',
  BUILD_DATE: '2016-01-19T21:11:30.293Z',
})
```

The gulp task also injects values not contained in `environments.json` (ex: `VERSION` and `BUILD_DATE`, but you could easily omit these).

Here is the important piece: **when I build `www` I must specify which environment to build against.** For example, I can run `IONIC_ENV=staging ionic serve` and it will run my Ionic app against our staging server API. When building for `ionic deploy` or the App Store, I run `IONIC_ENV=production gulp build`.

Here's the gulp task which compiles `./www/js/config.js` based on the requested environment:

```javascript
var gutil = require('gulp-util');
var replace = require('gulp-replace-task');

// Task which loads the requested environment config from environments.json
// and compiles app/config.js to www/js/config.js
gulp.task('config', function(done) {
  
  // (1) Determine which environment to use when building config.
  // Ex: IONIC_ENV=production gulp config
  var env = args.env || process.env.IONIC_ENV || 'development';

  // (2) Load & validate the environment:
  var environments = JSON.parse(fs.readFileSync('./environments.json', 'utf8'));
  var config = environments[env];

  if(!config) {
    gutil.log(gutil.colors.red("=> Could not load `" + env + "` environment!"));
    return done();
  }

  gutil.log(gutil.colors.green("Loading `" + env + "` environment..."));

  // (3) Add additional (dynamic) constants.
  // I also pluck the latest git commit info here, but have ommitted it.
  config['VERSION'] = JSON.parse(fs.readFileSync('./package.json', 'utf8')).version;
  config['BUILD_DATE'] = (new Date()).toJSON();

  // (4) Construct replacement patterns, ex: replace @@KEYS with real values.
  var patterns = Object.keys(config).map(function(key) {
    gutil.log(gutil.colors.green("=> " + key + ": " + config[key]));
    return {match: key, replacement: config[key]};
  });

  // (5) Perform the replacements and pipe to build folder.
  gulp.src('app/config.js')
    .pipe(replace({patterns: patterns}))
    .pipe(gulp.dest('www/js'));

  return done();
});
```

(PS: In the meantime, I would love any suggestions / feedback on how I could improve my current setup).

My biggest challenge is that configuration management is inexorably woven into the development & build process — an area where Ionic (currently) offers little guidance. The "out-of-the-box" approach Ionic offers (everything in `www`) probably works well for many small/simple apps but IMO doesn't scale very well once you add multiple developers, multiple environments, dependencies (ex: 14MB of bower modules), etc. So, I am not entirely sure how to come up with a simple convention for configuration management when there isn't (as far as I can tell) a convention around build processes.

I do kinda like the idea of using `BUILD_ENV=environment` to construct a generic configuration object from `environments.json`. It's not a complete solution, but could be a simple (platform-agnostic) first step.

Going a step further: I would love if, in my code, I could just use `Ionic.config.API_BASE_URL`, in much the same way I can access the current environment's config in Rails. There could even be an `Ionic.environment` attribute so that you can conditionally execute code in certain environments. Perhaps even `Ionic.Environment.name` and `Ionic.Environment.config`.

Anyway, just thought I'd share my current setup and spitball some ideas. Hope it's helpful in some way!

**Comment by AgDude** [comment]
@kylefox my setup is very similar to yours. I use [gulp-ng-constant](https://www.npmjs.com/package/gulp-ng-constant). I call these configurations, instead of environments, but the same idea. One nice thing about this tool is that I can have a base config and extend it for different environments. I have a single angular constant call `APP_CONFIG` which has all of the configuration.  Here is my gulp task for building the config.

```
gulp.src([paths.config + 'config-base.json', src])
    .pipe(extend('config.json', true))
    .pipe(ngConstant({
      deps: false,
      constants: { VERSION: package.version }
    }))
    .pipe(rename(function(path) {
      path.basename = 'config';
      path.extname = '.js/';
    }))
    .pipe(gulp.dest(dest));
```

`src` is a variable set based on arguments passed to the gulp task. You can see I also inject the version directly at build time.

**Comment by ericb** [comment]
@kylefox I think you bring a valid point that we should keep in mind when you touch on applications that need to scale both in code and team management. The usage of 'environment' is also something that is fairly universal (those that don't require an environment have no need for more than single setup, but everyone else can happily add multiple configs). 

We should be keeping in mind the usage of different version control systems as well (mostly in the way that there will be a mix of those who need their configurations in version control, and others who need to make sure it's not, or a combination of having a configuration, but that can be templated)

**Comment by kylefox** [comment]
@AgDude Thanks for mentioning [gulp-ng-constant](https://www.npmjs.com/package/gulp-ng-constant), this looks like a more elegant setup than what I patched together. I also like the idea of merging in config that is common for all environments. Do you have a different file for each configuration?

@ericb 

> The usage of 'environment' is also something that is fairly universal...

Yep — one thing I found interesting with the Ionic platform is that Ionic Deploy comes with Dev, Staging, and Production [Deploy Channels](http://docs.ionic.io/docs/deploy-channels), yet there is no official workflow around _building_ for these different environments. (I realize the idea behind Deploy Channels is to segment installs by user, not necessarily different configurations — but it still does show Ionic acknowledges that a real app will have various different builds for different users/scenarios).

> We should be keeping in mind the usage of different version control systems as well

Good point. Mapping config to environment variables (rather than hard-coding them into config files) is one approach. These placeholders could be injected at build time. Another approach is to allow specifying the configuration to use from the command line in a way that allows you to specify arbitrary configuration (`IONIC_ENV=beer_is_good gulp build`) and have it map to a specific file (`./config/beer_is_good.json`) which is compiled into an Angular constant. This way teams can choose whatever config files they want to be included or excluded from version control.

As I started to brainstorm some approaches, I realized none of this really addresses the initial problem of getting Ionic config into the Ionic bundle. Either (1) developers would need to manually insert their Ionic IO settings into config files, or (2) this scheme would need to include a way for third-parties to include configuration that gets compiled in to the final config object.

As I see it, this problem can be broken down into a few smaller problems:

1. How does the user specify which configuration "environment" to use?
1. Which configuration files get merged (including third-parties) for that environment?
1. In what order are the configuration files merged?
1. When/where does compilation (especially for dynamical values like `VERSION`) happen?
1. How do developers access the configuration from the app?

Does that sound about right? I hope I'm not confusing this thread :hamburger:

**Comment by kylefox** [comment]
I started thinking about what kind of generic set of conventions would work for me and the various uses cases I've encountered. I outlined one approach for creating framework-agnostic configuration for multiple environments which I think addresses the problems I listed above.

It's described (with examples) here: https://gist.github.com/kylefox/4dc10aa5beaf4409ce76

It may be far to complex, I might be missing obvious shortcomings, etc. Any feedback would be appreciated!

cc @AgDude @ericb

**Comment by ericb** [comment]
@kylefox Wow, what a write up! Thank you. I'm tied up at the moment so I can't take a deep dive into your examples, but rest-assured I will be looking at this when I can.

**Comment by kylefox** [comment]
@ericb No sweat — TBH after thinking about it more it's probably more complicated than necessary.

**Comment by mlynch** [comment]
I think we can simplify and remove some of the complicated automation here, and make Ionic Platform config more standardized with the rest of the industry, if we move to a simpler "snippet installation" process.

A user runs `ionic upload` or `ionic platform init` and then we print something like:

```bash
$ ionic platform init
Log in...
Email:...

Great! To get Ionic Platform installed, follow the installation instructions in your App Dashboard:

https://apps.ionic.io/app/939dd92a/settings/installation

We also have extensive documentation on the entire installation and usage of Ionic Platform: http://docs.ionic.io/docs/io-install
```

Then we go back to having them use a specific snippet in their `app.js` and add the required Angular module if using Angular:

```javascript
angular.module('myApp', ['ionic', 'ionic.services'])

.configure(['$ionicServicesProvider', function($ionicServicesProvider) {
  $ionicServicesProvider.init({
    app_id: 'blah'
  });
});
```

Or non-angular:

```javascript
var p = new Ionic.Platform();
p.init({
  app_id: blah
});
```

**Comment by kylefox** [comment]
@mlynch Yep, this would be great, simple, and is a huge improvement over the current setup :+1: 

However, some of this discussion is around Ionic providing a standardized way to inject arbitrary configuration that is not known until compile time (such as API base urls, etc). These are things that can't (and shouldn't) be hard-coded into the app itself.

**Comment by mlynch** [comment]
@kylefox I think, in practice, we will need to have a few API endpoints and paths hardcoded. However, I don't see any reason why certain portions of the API clients can't support overridden API urls. That being said, I don't see that being necessary or useful for end users, just Ionic Platform engineers.

As for hard coding API keys, etc. I think it'd be better to put that on the end user to configure if they like, and we just accept the string in the JS as in my snippet above. This would be most inline with existing APIs that require snippets (google analytics/mixpanel/intercom/etc.)

**Comment by kylefox** [comment]
(@mlynch  sorry, I hit enter prematurely — you may not have seen the rest of my previous comment)

**Comment by kylefox** [comment]
Also, to clarify, I mean _my_ API URLs. For example, I might want my API root to be:

* `localhost:8000` during local development
* `staging.example.com/api/` with beta testers
* `api.example.com` when building for app store

**Comment by pascalwhoop** [comment]
The current situaiton forces us to keep the /www/lib folder in the git repo because there is production relevant code in side of the modified vendor js files. Thats very bad practise. Also if you do `ionic io init` on a machine with the `.io-config.json` already being present, it is ignored and just overwritten. Even if I login to an account that has the exact app already in the cloud + the config in the local folder. Why does it behave this way?

**Comment by meticoeus** [comment]
If Ionic goes with the snippet configuration approach for the ionic platform config, it would at least be compatible with using a compile-time injection of environment configuration approach used by @kylefox and others.  We could simply replace the hard coded keys provided in the snippet with variables for replacement like `@@IONIC_APP_ID`.

As long as the snippet operates in the angular configure step, it would also support gulp-ng-constants as well.

**Comment by ericb** [comment]
#### Update Time!

I've started an early PR #84 to support Ionic 2, but it will also contain the configuration update. Based on some of the feedback here, it seems like the "simpler" approach would be the best fit to ensure that any workflow can be built around individual needs. With that in mind, I think we go back to a simple snippet approach that @mlynch mentioned.

The platform would require a configuration object to be passed directly via code (keeping it completely open-ended in terms of how it gets there). 

Let's look at an "at a minimum" example:

```javascript
Ionic.Core.setConfig({
  app_id: "16c5e925",
  api_key: "1ed65e5be02eec7a6814edc598e2ecd593cdfd91f41a46ca"
});
```

This would need to be set before interacting with any of the Ionic Platform services and I would recommend that this would _conventionally_ be setup in a `ionic.platform.config.js` file that the developer would create and include in their `index.html`

This would allow for very straightforward examples in both code and documentation, but also lends itself to an easy transition for custom workflows where the configuration itself is generated by an external process. This has the further added benefit that the configuration file is not tied to any specific location, meaning custom app structures are also supported out of the box.

#### What about environments, and variable replacement, etc?

Nothing that I've outlined so far would have this experience "baked in", but it would not prohibit it either. I think there is definitely room for us to provide a "baked in" experience here (especially one that is optionally used rather than enforced) -- but I'm not going to try and squeeze that in with this update just yet...

I'd like to first get a better configuration in your hands and then build an optional environment workflow on top of that.

#### Conclusion

When the PR is complete the following would be considered solved:

* Remove code modification for configuration
* Support custom app structures
* Configuration can be generated via a custom process

The following will _not_ be added with the PR:

* Having Environments baked in
* Variable Replacement (selective overrides)

**Comment by kylefox** [comment]
@ericb This approach totally makes sense to me :+1:

**Comment by AgDude** [comment]
I'll second that. Looks great.

I would advise against "baking in" environment variable support, as long as you have something as simple and flexible as what is described, I see no advantage. Beginners won't use it, and advanced users will almost certainly have other things impacted by those build configurations which you won't be able to plan for.

**Comment by mlynch** [comment]
Much better. Let the tooling (gulp/etc.) handle variable/environment config if a dev wants to use it, we shouldn't touch that IMO.

I don't have a strong opinion on the `ionic.platform.config.js` convention except that I don't think we need to push it too hard in docs, we can provide a default out of the box we like in our own examples but not prescribe much beyond that

**Comment by meticoeus** [comment]
I think this approach makes sense, allowing for maximum tooling compatibility.

However, it might not be bad idea if the default tooling that is setup for you when you create a new ionic project (with the CLI) incorporates flexible environment variable support baked with a default configuration that 'just works' for the hello world getting started users.

Ionic 1 gives you a gulp script to compile Sass files which I eventually extended for all of the other stuff our project needs. I haven't made time to try Ionic 2 yet but I'm sure it does something similar. I think that is be the best place for Ionic to provide for a convention around tooling.

**Comment by gruppjo** [comment]
Hi everybody:)

I'm currently integrating the `ionic-platform-web-client` and the **Ionic CLI Platform commands** into [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic) and I stumbled upon this issue, since I ran into similar problems with the current configuration setup.

## Current PR
I really like the course of this discussion and the simplicity and flexibility of @mlynch's approach. It removes the necessity of editing the library code effectively -which I think is the most annoying part for all of us- and thus makes workarounds like custom gulp tasks obsolete. Nice! Can't wait for the PR to go live @ericb, any estimate on when it'll be ready, merged and released? 

Will this PR also support @mlynch's example of how to integrate this into angular using `$ionicServicesProvider`?
```js
angular.module('myApp', ['ionic', 'ionic.services'])

.configure(function ($ionicServicesProvider) {
  $ionicServicesProvider.init({
    app_id: 'blah',
    api_key: 'moreblah'
  });
});
```
That would help **a lot!** Let me explain:

## Environments and such
I also think that managing different environments and such is better covered in other places. 

@kylefox, @AgDude I agree with many of the things you wrote about application structure and the dev/build process as well as many other statements you made. So I thought it might be of interested to you and the rest of you guys that our [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic) comes with an **elaborate environment system that does just that**. Out of the box. 

It supports injecting different environments and build-parameters into an angular constant called `Config` which is generated for you. Injection is possible during `gulp watch` or `gulp build` and many other tasks. With that, developing and building for different environments is really easy.

Incidentally this **would already support** @mlynch's approach, so it would be **really really great** if the configuration via `$ionicServicesProvider` was supported in your PR @ericb. You could either make the `api_key` and `app_id` a part of your environment if you have to manage different ones, or you can just hard-code it into the `Config` constant. Here's two examples without going into the details too much:

#### Using Environments
Suppose you have two environments `dev` and `prod` (they're managed via json files). When you now run `gulp watch --env=prod` or `gulp build --env=dev` you can easily switch your app's `app_id` and `api_key` as they are injected into `Config.ENV`.

The following setup then wires the correct values into your app:
```js
angular.module('myApp', ['ionic', 'ionic.services'])

.configure(function ($ionicServicesProvider, Config) {
  $ionicServicesProvider.init({
    app_id: Config.ENV.app_id,
    api_key: Config.ENV.api_key
  });
});
```

#### Hard-coded in Config
Alternatively if you don't need different values for prod and dev, you can just hard-code them into your `Config` constant and thus wire the `api_key` and `app_id` into your app like this:

```js
angular.module('myApp', ['ionic', 'ionic.services'])

.configure(function ($ionicServicesProvider, Config) {
  $ionicServicesProvider.init({
    app_id: Config.app_id,    // no .ENV here!
    api_key: Config.api_key  // no .ENV here!
  });
});
```
More info on:
- our generator [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic) (check out the README)
- our [environment](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/environments.md) system
- our [build-vars](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/build_vars.md) system (which also uses the `Config` constant)

I thought this might be of interest to you. Feedback very welcome.

## Current Integration into our generator
For the time being I wrote a gulp task, that injects the `api_key` and `app_id` into the library files and a guide on how to use the ionic platform with our generator. Both of which I will release soon. In case you're interested:

- preview the guide [here](https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/ecosystems/ionic_platform.md).
- more info on the gulp task in this issue: https://github.com/driftyco/ionic-platform-web-client/issues/4#issuecomment-211885058

Thank you, keep up the good work!

**Comment by iabdulin** [comment]
Replacing `"IONIC_SETTINGS_STRING_START";"IONIC_SETTINGS_STRING_END";` is a super sneaky way to configure smth :)
It took me couple hours to understand why ionic-platform-web-client doesn't work with my webpack & npm setup

**Comment by iabdulin** [comment]
Another thing I would like to mention:
currently I have 3 files for ionic config: 
- ionic.config.json
- .io-config.json
- ionic.project

It would be nice to have just 1 json file with all config in 1 place

**Comment by genox** [comment]
Great to see that this is being addressed already! Looking forward to test.

**Comment by dwieeb** [comment]
Hey all. I believe I've addressed all the issues with our config in the current beta of the Cloud Client. Can I get some people to test it? Here are the [setup instructions](https://github.com/driftyco/ionic-cloud#readme). Don't try on an existing app. There have been some breaking changes in push and deploy that are not yet documented (a migration guide is coming).

I'm closing this issue for now, but I would appreciate [feedback here](https://github.com/driftyco/ionic-cloud/issues/3). You can also open issues regarding the beta in the new repo. 👍

**Comment by AgDude** [comment]
@dwieeb I just went to try out your new cloud client, but it doesn't look like there is support for analytics yet. do you have an estimate on when that will be available? I would certainly appreciate some more comprehensive docs as well. I have 2 ionic apps in production which currently do not use platform at all, and if there is a reasonable configuration method and relatively stable api I would like to start using it.

**Comment by dwieeb** [comment]
@AgDude I'll be adding it back soon. We're also currently writing our new docs. A *lot* of things are happening right now!

**Comment by dr3x** [comment]
I know this is an old closed thread but maybe someone knows how to configure this:
My app pulls data from json files via a provider; these data files should deploy with the app.
Initially I had them under the src/app folder but they weren't getting served so I moved them to the www folder however that is ignored which makes sense because the www / dist folder is rebuilt from source.  Where should these files go to get properly deployed?  I'd rather not have to individually specify them in the build configuration.

**Comment by genox** [comment]
@dr3x You could bundle the data with the service/component. Depending on the size of it, of course. Or push it to firebase.
