### ISSUE TITLE
bug: Push not working properly

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-platform-web-client#45]
_From @upmauro on January 20, 2016 20:57_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>

### Ionic

Component | Version
---------------|-----------
Cordova CLI | 5.4.1
Ionic Version | 1.2.4-nightly-1917
Ionic CLI Version | 1.7.12
Ionic App Lib Version | 0.6.5
Node Version | v5.3.0

### Android

Component | Version
---------------|-----------
SO| 6.0
SDK| 23 

### Problem

I am using the ionic to receive push messages. All messages arrive correctly on the device, however, are displayed in the status bar, but without running the code defined in the notification event (onNotification).

```javascript
angular.module('app', ['ionic', 'ionic.service.core', 'ngCordova'])
.run(function($ionicPlatform, $rootScope, $state, $ionicHistory) {

    $ionicPlatform.ready(function() {
        var push = new Ionic.Push({
            "onNotification": function(notification) {
                console.log('Push received.')
                navigator.vibrate(700);
            },
        });
    })

});
```
The above is only triggered after clicking on the notification.
I already tried everything I found solution and it still fails.
Could you help me?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5113_

**Comment by ericb** [comment]
@upmauro Everything is working as intended. The application cannot currently run your callback unless the application is actually running. However, you if you take a look at the [push plugin options](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md) you can see several options which can have an effect on the device when a notification is received.

**Comment by upmauro** [comment]
@ericb  thanks for your reply and for contributing to this amazing project. Just one more question, following the best practices, how to record the notification event in a localStorage being the onNotification event will be called only in case the user click?

**Comment by ericb** [comment]
@upmauro Thanks for the kind words! As far as I know, what you're asking is impossible without the usage of native code (a cordova plugin may exist for this, but I have not personally looked into it). This is because the callback is in javascript, which requires that the application be running in order to call it. 

If you're using the push notification to set some kind of metadata in your application, you may want to look into using [background notifications](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md), however, the necessary call to `finish()` is currently lacking in the platform web client -- the next release will include a `getPlugin` call that you use to call finish on.
