### ISSUE TITLE
Suggestion: add `Ionic.User.clear()`

### ISSUE THREAD

**Issue by kylefox** [driftyco/ionic-platform-web-client#51]
I ran into an issue using `Ionic.User.current()` during my login/logout flow: 

```javascript
var ionicUser = Ionic.User.current();
ionicUser.id = user.id.toString();
ionicUser.save();
```

It works fine when I login as user_1, but when I logout and login as user_2 it results in a 404 because it's attempting a PUT request to user with ID=2. _However, if I refresh the page before logging in as user_2 it works as expected._ From what I can tell this is because user_1 is still saved in memory and localStorage. Thus, the API thinks I'm updating an existing user rather than creating a new user.

To get around it I use `new Ionic.User()` rather than `Ionic.User.current()` and it works as expected:

```javascript
var ionicUser = new Ionic.User();
ionicUser.id = user.id.toString();
ionicUser.save();
```

So, I have a few ideas:

1. **Documentation:** explain that `new Ionic.User()` can (and should) be used when the user context changes (ex: signup, login). Currently the docs to not even mention that direct instantiation is allowed.
1. **Documentation:** make it more explicit that `Ionic.User.current()` will _always_ fetch the cached user, and should only be relied upon _after_ the correct user has been set via `new Ionic.User()`.
1. **API:** Add a `Ionic.User.clear()` method that will nuke the Ionic user object from memory and localStorage, and explain that it can be called at logout.

The API use would look like:

1. Use `new Ionic.User()` at login.
1. Use `Ionic.User.current()` during the session (for performance).
1. (Optional) Use `Ionic.User.clear()` to clear the cached user object at logout.

I wanted to post this issue before making doc edits or pull-requests, just to make sure my understanding of how the User system works is correct.

Thanks!

**Comment by ericb** [comment]
I agree 100% that we need to update documentation. We've got some upcoming changes for Users and handling login coming soon so I will be sure to address the documentation along with that.

I also like the concept of having a `clear` or `reset` method that will wipe any user context. If you'd like to work on a PR for this I'd be happy to review it and pull it in, otherwise I will most likely add it in the next batch of updates.

As for your current flow, you can update the *current* user with another user by passing a user object to the `current` method:

```javascript
// set a new user object as the current user
var newUser = new Ionic.User();
Ionic.User.current(newUser);

// or set it as a newly loaded user
Ionic.User.load('user-id').then(function(loadedUser) {
  Ionic.User.current(loadedUser);
});
```

If you use the new Ionic.User with an id of a previously created user, it will not have the data that was previously stored on that user.  Using the `load` approach will make sure get the user with all their details. Just be aware that you'll need to make sure the obj you assign Ionic.User.current() too will be outdated if you use it before the load has finished.

As a side note, I think you will be pleased with the upcoming changes, so you may want to hold off a bit before diving too deep into the User codebase.

Cheers :beers:

**Comment by kylefox** [comment]
Awesome, thanks for the details!

> If you'd like to work on a PR for this I'd be happy to review it and pull it in

I'll likely hold off if there are some changes coming down the pipe relatively soon.

I had considered submitting a PR for this as well as #50 but wasn't sure what your contributing guidelines were — for example, I don't see any tests. Do people typically just fork, smoke test locally, and then submit a PR?
