### ISSUE TITLE
Ionic Deploy: Update error!  download error

### ISSUE THREAD

**Issue by webdigi** [driftyco/ionic-platform-web-client#54]
So, we have an ionic app and it is all linked up correctly. ionic upload shows the latest update in ionic.io apps and i can deploy the app.

however when i go in for download on iOS it says "Ionic Deploy: Update error!  download error"

I can see the S3 URL for download but when accessing that S3 URL it says attached
![error-s3](https://cloud.githubusercontent.com/assets/467830/12747151/382db99a-c99a-11e5-8ec5-e74c4b42a153.png)

**Comment by ericb** [comment]
Are you getting this from every deploy, or only this one specifically? It's possible the file failed to transfer to S3 correctly.

**Comment by webdigi** [comment]
Getting this for every deploy on my new project. I tried a couple and still has the same problem.

**Comment by ericb** [comment]
Are you sure you've configured the project correctly? If you're on iOS9 you'll need to allow an exclusion rule for S3 servers (see the note about this on the [docs](http://docs.ionic.io/v1.0/docs/deploy-install)).

**Comment by webdigi** [comment]
The same error should on simulator and phone when tried with iOS 8 and iOS 9. All deploys and updates required are being red correctly, however the update does not happen.

Please see attached
![error-with-update](https://cloud.githubusercontent.com/assets/467830/12750384/bfa887e2-c9ae-11e5-9e96-99de37cd9ab8.png)

What do you think we are missing.

**Comment by ericb** [comment]
It looks like something may be wrong with your upload attempts. What version of the CLI are you using to upload? You can see the version by running: `ionic info`

**Comment by webdigi** [comment]
Your system information:

Cordova CLI: 5.4.1
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
OS: Windows 7
Node Version: v4.2.4

**Comment by webdigi** [comment]
Yes, thanks it works now. It was a problem with uploading on windows machine. Tried on a MAC and it works as expected.

Any ideas how to fix the issue on windows?

**Comment by ericb** [comment]
I'm not certain what the actual is -- could be a number of different things, some of which could be on the CLI, others could just be with your machine. Do you have any other windows machines you can test with?

What version of windows are you running?

**Comment by webdigi** [comment]
windows 7. no other windows machines to test with. It might have to do with a slow connection on the windows 7 box? it takes about 8 minutes to upload so it might not have completed or uploaded fully. Although there are no errors of a failed upload and everything seems fine from .

Shall I close this?

**Comment by ericb** [comment]
It's definitely possible it has a slow connection and errors on that connection. I'll close for now, but if you can replicate this on other machines in the future, feel free to comment and we can reopen.

**Comment by sylfree9999** [comment]
Hi @ericb , @webdigi , I'm facing the same issue here but the thing is I could not even download successfully using the mac(but uploading is a success). 

I guess this might because of the internet connection(quite slow and could not connect to some certain websites... thanks to our coutry), so I changed the download url to our server to get the www.zip, then it downloaded successfully but failed to redirect to new page.

Here is how I get the www.zip: I compress the www folder that listed in the xxx.app package, so it will include something like cordova.js, then upload this zip to our server(not aws). 

I tried to copy the aws address like webdigi did, but the error shows the specified key not exist, just like webdigi.

So did I upload the correct www.zip? Why the redirect fails?
![downloaderror](https://cloud.githubusercontent.com/assets/15099465/15286556/61a09250-1b90-11e6-8430-0b3b52913a1a.png)
