### ISSUE TITLE
How can i get a list of invalid tokens ?

### ISSUE THREAD

**Issue by youssmak** [driftyco/ionic-platform-web-client#89]
I know i can get a list of the recent tokens created with 
`https://api.ionic.io/push/tokens`

But is there a param to get only invalid tokens ? (or a pager at least)

I need a list of invalid tokens to clean my database and not send push notifications to users who have uninstalled the app.

**Comment by Fuiste** [comment]
@youssmak that's not something the endpoint currently offers, but it should be noted that any users who uninstalled the app will not be able to receive notifications from it, and any attempts to push to their tokens will give some kind of invalid token error in their status.  You could remove references to invalid tokens in this manner.

**Comment by youssmak** [comment]
@Fuiste thank you for you response.
You mean i have to check after an X minutes timeout the status of each sended push notification via /notifications/notificationId/messages to get the invalid tokens ?
Not really practical ...

**Comment by ericb** [comment]
@youssmak You can pass an optional [show_invalid](http://docs.ionic.io/v2.0.0-beta/docs/api-push#tokens-list) param to the token listing endpoint to show invalid tokens alongside valid ones. You can periodically go over all your tokens in this manner and invalidate tokens on your end.

**Comment by youssmak** [comment]
@ericb thank you

**Comment by youssmak** [comment]
@ericb It seems that https://api.ionic.io/push/tokens?show_invalid=true shows also valid tokens ?
`
{
      "invalidated": null,
      "created": "2016-04-13T14:25:27.563089+00:00",
      **"valid": true**,
      "app_id": "example",
      "type": "ios",
      "token": "example",
      "id": "bc1e51248fbe8c5de5dfcbbc97f403e1"
    }
`

**Comment by ericb** [comment]
Yup, that is the intended purpose of the filter.

**Comment by youssmak** [comment]
@ericb i'm sorry but i don't understand.
How can i get only invalid tokens ?

**Comment by ericb** [comment]
We don't offer an endpoint to only list invalid tokens at this time -- you can get all your invalid tokens in the same way you would get a list of all your tokens. 

Using the endpoint I previously provided in combination with pagination, you can get a listing of all of your tokens. You'll need to check the `valid` property of each token to see if it's currently invalid.

For example, let's say you have 500 tokens, you could make a request to that endpoint such as:

    https://api.ionic.io/push/tokens?show_invalid=true&page=1&page_size=100

You could then make a call to the 2nd page of results:

    https://api.ionic.io/push/tokens?show_invalid=true&page=2&page_size=100

And so on until you receive an empty set of data.

**Comment by youssmak** [comment]
@ericb thank you. I was not aware about pagination. 
This is not a convenient solution, I hope this will evolve.

**Comment by youssmak** [comment]
@ericb any news on this ?
Are notifications sent to invalid tokens are included in the quota ?  http://ionic.io/pricing

**Comment by ericb** [comment]
We have not implemented on changes on the api to list only invalid tokens, but invalid tokens are only included as part of the quota when they were *not* previously invalid. So as an example, lets say you register 3 tokens [Token A, Token B, Token C]

Now you send to all 3 tokens. None of them were currently marked as invalid, but the response from APNS/GCM said that Token C is invalid (we then mark Token C invalid).

3 messages would have been counted as part of your quota, even though 1 came back as invalid, we still went through all steps as though it were not invalid.

Now you send to the same 3 tokens again. Because Token C was previously marked as invalid, we only send messages to Token A and Token B. So this time we only add 2 messages to your usage because we did not attempt to send to the 3rd token. This will continue to be the case unless you mark the invalid token as validated, in which case we would retry sending to that token.

So, even though you sent to six tokens total, we would have only tracked 5 of them as real usage.

**Comment by youssmak** [comment]
thank you for your quick reply 👍
